// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFB8Kyh32nEH-98SuUgWJl59mEuuMtw20',
    appId: '1:254618248942:web:1ae6cbe99b92d7632eb5ff',
    messagingSenderId: '254618248942',
    projectId: 'phone-store-project',
    authDomain: 'phone-store-project.firebaseapp.com',
    databaseURL: 'https://phone-store-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'phone-store-project.appspot.com',
    measurementId: 'G-HDGP8JJT1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB4Hfujg7mtFnJWUmMQCvZXoSbXI4ozts',
    appId: '1:254618248942:android:82a2e450983adc032eb5ff',
    messagingSenderId: '254618248942',
    projectId: 'phone-store-project',
    databaseURL: 'https://phone-store-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'phone-store-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz1RQvHrO0Cj75a_hPl5slCO-dXFsRB9w',
    appId: '1:254618248942:ios:6bd7c3398e15c3382eb5ff',
    messagingSenderId: '254618248942',
    projectId: 'phone-store-project',
    databaseURL: 'https://phone-store-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'phone-store-project.appspot.com',
    iosBundleId: 'com.example.phoneStoreApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz1RQvHrO0Cj75a_hPl5slCO-dXFsRB9w',
    appId: '1:254618248942:ios:bf7a220166eb16d22eb5ff',
    messagingSenderId: '254618248942',
    projectId: 'phone-store-project',
    databaseURL: 'https://phone-store-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'phone-store-project.appspot.com',
    iosBundleId: 'com.example.phoneStoreApplication.RunnerTests',
  );
}
